version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  db:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
      # PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  application:
    container_name: app_spring
    build:
      context: ./sport
      dockerfile: Dockerfile
    links:
      - db
      - rabbitmq
    ports:
      - 8080:8080
  parser:
    container_name: parser_spring
    build:
      context: ./parser
      dockerfile: Dockerfile
    links:
      - rabbitmq
      - application